language: python
python:
  - "2.7"
  - "3.3"
env:
  - DJANGO_VERSION=1.5
  - DJANGO_VERSION=1.6
install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -q -r tests/requirements.txt
script:
  - cd tests
  - python manage.py test
